### ISSUE TITLE
Package not using CUDA

### ISSUE THREAD

**Issue by Mvb1122** [jose-solorzano/audio-denoiser#2]
Hello, I'm having a problem with this package. It seems like it's not using CUDA at all on my machine! I've verified that CUDA is working just fine; in fact, I'm running models on CUDA in the same file as I call this model.

Here's my relevant code. Let me know if you need more details.

```python
import torchaudio
from audio_denoiser.AudioDenoiser import AudioDenoiser

device = "cpu"
if (torch.cuda.is_available()): device = "cuda:0"
# ...
denoiser = AudioDenoiser(device=torch.device(device))
# ...
signal, fs = torchaudio.load(source)
auto_scale = True # Recommended for low-volume input audio
signal = denoiser.process_waveform(waveform=signal, sample_rate=16000, return_cpu_tensor=True, auto_scale=auto_scale)
```

It seems to work as is, but I'd like to get it to run on CUDA if possible.

Thanks,
Micah

**Comment by jose-solorzano** [comment]
Hi Micah,

I double-checked the code. AudioDenoiser uses the device to do inference on
the model. However, conversion from waveform to spectrogram and vice versa
is done in the CPU. You can check the *device *property of the
AudioDenoiser instance to see if it's what you expect. The model is
necessarily in the given device.

Is it because of performance that you believe CUDA is not being used?

Jose

**Comment by Mvb1122** [comment]
Yeah, I guess it's because I saw only a small spike of CUDA activity and then a long burst of CPU activity that I thought it was mainly using the CPU for stuff. But, if it's intended behavior, then I guess it's okay 👍 

Thanks for your help
Micah

**Comment by jose-solorzano** [comment]
I've pushed an update (version 0.1.2) where not just inference, but also spectrogram handling, can run in CUDA. Closing issue.
